syntax = "proto3";

package wellai_bot.agent;

import "proto/common/common.proto";

// Message sent by user
message Message {
	string user_id = 1;
	string content = 2;
}

// AI Agent Service
service AgentService {
	// Receive messages from user via client streaming (send by bot service)
	rpc Receive(stream Message) returns (wellai_bot.common.Response);

	// Bidirectional streaming: receive messages and stream back responses
	rpc ReceiveAndRespond(stream Message) returns (stream wellai_bot.common.Response);
}
